kumuluzee:
  name: basketball-leaderboard
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8087
    http:
      port: 8087
  datasources:
    - jndi-name: jdbc/leaderboardDS
      connection-url: jdbc:postgresql://pg-events.clvqrwayazxs.eu-central-1.rds.amazonaws.com/leaderboard
      username: postgres
      password: postgres12
      max-pool-size: 3
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/leaderboardDS
  metrics:
    web-instrumentation:
      - name: leaderboard-endpoint
        url-pattern: /v1/leaderboard/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="906c451a-bc58-4cb6-8145-6a2d768e120b-ls.logit.io"
                                  port="26828" protocol="UDP">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="info" />
                                  </Root>
                              </Loggers>
                          </Configuration>'
  rest-client:
    registrations:
      - class: leaderboard-api
        url: http://localhost:8087/v1
        read-timeout: 5000
rest-config:
  maintenance-mode: false
  api-token: htn12kss3